global:
  message: Welcome to order service prod environment
server:
  port: 8083
message: Hello from Order Prod
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/order_prod
    username: root
    password:
  jpa:
   hibernate:
    ddl-auto: update
  show-sql: true
